### ISSUE TITLE
Workaround for usage with sidebarmarkers component

### ISSUE THREAD

**Issue by Plastikmensch** [Plastikmensch/dynmap-mobs#12]
It is not recommended to use dynmaps undocumented sidebarmarkers component with this plugin, as it causes a huge memory spike on dynmap, which causes OOM.

Ideally this should be fixed upstream by adding an optional config key to markersets like "showonsidebar" which defaults to false.

### Step one:
Edit sidebarmarkers.js
**This has to be done every time you update dynmap**

In the UpdateMarkers function change:
```
$.each(markersets, function (key, set) {
	if (!set.markers || $.isEmptyObject(set.markers)) {
		return;
	}
```
to:
```
$.each(markersets, function (key, set) {
	if (!set.markers || $.isEmptyObject(set.markers) || (!cfg.enabled_sets.includes(set.label) && !cfg.enabled_sets.includes(set.id))) {
		return;
	}
```
### Step two:
Enable sidebarmarkers and markersets in configuration.txt
```
# Enable undocumented sidebarmarkers. Shows markers in sidebar.
  - class: org.dynmap.ClientComponent
    type: sidebarmarkers
    title: 'Markers'
    # List of enabled sets
    enabled_sets:
      - "markers"
```
enabled_sets works with label and id. "markers" is the id of the default markerset.
